Vagrant.configure("2") do |config|

  config.vm.define "server" do |server|
    server.vm.box = "bento/ubuntu-16.04"
	server.vm.network "public_network"
  end

  config.vm.define "host" do |host|
    host.vm.box = "bento/centos-7.4"
	host.vm.network "public_network"
  end
  
end
