Vagrant.configure("2") do |config|

  HOSTS = [
    { :box => "bento/ubuntu-16.04", :hostname => "ubuntu", :ip => "192.168.68.10" },
	{ :box => "bento/centos-7.4", :hostname => "centos", :ip => "192.168.68.11" }
  ]
  
  # Set up hosts(s).
  HOSTS.each do |host|
    config.vm.define host[:hostname] do |box|
      box.vm.box = host[:box]
      box.vm.hostname = host[:hostname]
      box.vm.network "private_network", ip: host[:ip]
    end
  end
  
end
