Vagrant.configure("2") do |config|

  config.vm.define "server" do |server|
    server.vm.box = "bento/ubuntu-16.04"
  end

  config.vm.define "server" do |host|
    server.vm.box = "bento/centos-7.4"
  end
  
end
